language: java

jdk:

- oraclejdk8

cache:

  directories:

  - "$HOME/.m2"

sudo: required

services:

- docker

notifications:

  email:

  - lightdynamics@foxmail.com

  on_success: always

  on_failure: always

branches:

  only:

  - master
